[tool.poetry]
name = "znsocket"
version = "0.1.0"
description = ""
authors = ["Fabian Zills <fzills@icp.uni-stuttgart.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-socketio = {extras = ["client"], version = "^5.9"}
eventlet = "^0.36"
typer = "^0.12"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.4"
pytest = "^8.2.1"
numpy = "^1.26"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
znsocket = "znsocket.cli:app"
